### ISSUE TITLE
Feature request: report failed test comments in summary

### ISSUE THREAD

**Issue by vrurg** [Raku/tap-harness6#34]
I'm currently trying to catch a flip-flop failure of a `roast` test which only takes place under harness and only when tests are executed as a batch, i.e. with `make spectest`, or `make m-spectest6`. Unfortunately, I have no other information but that test somehow fails. I can't run it in verbose mode a pass to `tee` or `less`:

```
Unhandled exception in code scheduled on thread 4
Cannot flush handle: Failed to flush filehandle: Operation not supported
  in block  at /Users/vrurg/src/Perl6/rakudo/t/packages/tap-harness6/lib/TAP.pm (TAP) line 927
```

It'd be great if comments following failed test are collected and reported at summary section when requested. Say, with an environment variable set or with volume set to `Normal`.

**Comment by Leont** [comment]
This error imples a bug in `TAP` itself, but it isn't clear to me how to reproduce this.

**Comment by vrurg** [comment]
It was way too long time ago, I hardly recall all the details. Perhaps worth closing this issue and see if similar kind of situation would repeat some day.
