### ISSUE TITLE
Please tag your releases

### ISSUE THREAD

**Issue by dod38fr** [Raku/tap-harness6#39]
Hello

I'm part of the Debian team that package Tap::Harness6 (and other Raku modules) for Debian.

I've seen that you have bumped Tap::Harness to version 0.1.0 but there's no matching tag in your repo. This is a problem for us because some of our tools rely on git tag to identify a new release. Without tag, Tap::Harness6 on Debian might get stale because we won't notice that a new version is available.

So could you please tag version 0.1.0 ?

All the best

Dod (for Debian)

**Comment by ugexe** [comment]
v0.1.0 release tagged -- https://github.com/Raku/tap-harness6/releases/tag/v0.1.0

**Comment by lizmat** [comment]
@dod38fr Thanks for the headsup.  @ugexe Thanks for the tag!

**Comment by Leont** [comment]
I'll try to pay more attention to it. `mi6` isn't handling this distribution well (because it doesn't understand having multiple classes in one compilation unit), therefore I have to do things manually that in other distributions happen automatically.

**Comment by dod38fr** [comment]
@ugexe thanks for the tag. That was fast !! :-)
