### ISSUE TITLE
Docker  image isn't working for poweron -ppc64le

### ISSUE THREAD

**Issue by asellappen** [Raku/tap-harness6#40]
resolvconf
services
3.02s$ sudo systemctl start docker
git.checkout
0.54s$ git clone --depth=50 --branch=master https://github.com/asellappen/tap-harness6.git asellappen/tap-harness6
0.01s$ bash -c 'echo $BASH_VERSION'
4.3.48(1)-release
install
2.89s$ docker pull jjmerelo/test-perl6
0.79s$ docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/test-perl6
standard_init_linux.go:211: exec user process caused "exec format error"
The command "docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/test-perl6" exited with 1.
Done. Your build exited with 1.

starting dokcr image is failing on power on , Its probably due to the fact that the image isn't compiled for poweron -ppc64le,Can you check ?

**Comment by JJ** [comment]
It's definitely not, unless Docker Hub does that for you. I'll have to try a way to do that. Any hint is appreciated.

**Comment by asellappen** [comment]
I have the job reference where its failed https://travis-ci.com/github/asellappen/tap-harness6 currently, will that help you for further investigation ?

Thanks

**Comment by seth-priya** [comment]
Hi @JJ there are a couple of ways I can suggest,

1- The images for ppc64le can be built and pushed manually by doing native builds on ppc64le VMs available via OSU, OSL https://osuosl.org/services/powerdev/request_hosting/ (do let me know if you choose to go via that path and I can share more specific details). Once the Power images are published, multiarch manifests can be used https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ to ensure support across different architectures, this would need to be created and published as well.
2- The process can be automated via travis-ci using multi-stage travis builds as shown here https://www.youtube.com/watch?v=_PbpRETbpow
3- not ideal from a performance perspective, but we can do cross-builds using docker buildx.

Hope that helps, please let me know if you have questions and I will be happy to answer!!

**Comment by JJ** [comment]
Thanks! I'll probably use the easiest way which seems to be 2.

**Comment by Leont** [comment]
I think #53 has superceded this issue
